<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.8.3 setup script
 * Date: Thu, 04 Oct 2018 02:45:00 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: mariadb [1] */
$i++;
$cfg['CheckConfigurationPermissions'] = false;

$cfg['Servers'][$i]['verbose'] = 'mariadb';
$cfg['Servers'][$i]['host'] = '192.168.99.100';
$cfg['Servers'][$i]['port'] = 32809;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'osp';
$cfg['Servers'][$i]['password'] = 'osp';
$cfg['Servers'][$i]['pmadb'] = 'green';

/* End of servers configuration */

$cfg['blowfish_secret'] = 'E;)SqzFdu(kWe2dN\\|74m>x3T{zj2Qc7';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>
